- name: INSTALL PHP 5.6 AND MYSQL 5.5
  hosts: dbserver
  become: yes
  become_method: su
  vars:
    applist:
      - acl
      - curl
      - zip
      - unzip
      - git
      - apache2
      - samba
      - smbclient
      - cifs-utils
      - libncursesw5
      - libaio1
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - php5.6
      - php5.6-cli
    enablemods:
      - rewrite
      - env
      - php5
  tasks:
  - name: install curl
    ansible.builtin.apt:
      name: curl
  - name: ADD PHP repository
    ansible.builtin.command: 
      curl -ssL -o /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
  - name: ADD TO SOURCES
    ansible.builtin.command: 
      sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
  - name: INSTALL ALL PACKAGES
    ansible.builtin.apt:
      name: "{{ item }}"
      update_cache: true
    loop: "{{ applist }}"
  - name: ENABLE APACHE MODS
    community.general.apache2_module:
      state: present
      name: "{{ item }}"
    loop: "{{ enablemods }}"
  - name: WGET INSTALL
    ansible.builtin.command: 
      wget -nc "https://downloads.mysql.com/archives/get/p/23/file/mysql-5.5.62-linux-glibc2.12-x86_64.tar.gz" -P /tmp
  - name: CREATE FOLDER
    ansible.builtin.file:
      path: /usr/local/mysql
      state: directory
  - name: UNARCHIVE
    ansible.builtin.unarchive:
      src: /tmp/mysql-5.5.62-linux-glibc2.12-x86_64.tar.gz
      dest: /usr/local/mysql
      remote_src: true
      extra_opts: [--strip-components=1]
  - name: CREATE GROUP
    ansible.builtin.group:
      name: mysql
      state: present
  - name: CREATE USER
    ansible.builtin.user:
      name: mysql
      state: present
      group: mysql
  - name: Check if Service Exists
    stat: path=/etc/init.d/mysql.server
    register: service_status
  - name: Init mysql db
    ansible.builtin.shell: |
        export PATH=$PATH:/usr/sbin
        echo "mysql service not exist proceed to install"
        cd /usr/local/mysql
        chown -R mysql:mysql *
        scripts/mysql_install_db --user=mysql
        chown -R root .
        chown -R mysql data 
        cp support-files/my-medium.cnf /etc/my.cnf 
        #bin/mysqld_safe --user=mysql
        cp support-files/mysql.server /etc/init.d/mysql.server
        #bin/mysqladmin -u root password 'pswd'
        update-rc.d -f mysql.server defaults  
        ln -s /usr/local/mysql/bin/mysql /usr/local/bin/mysql
    when: service_status.stat.exists == false
    args:
      executable: /bin/bash
    register: sqllog

  - debug: var=sqllog.stdout_lines
  - name: Retart mysql
    ansible.builtin.service: 
      name: mysql
      state: started