- name: INSTALL PHP 5.6 AND MYSQL 5.5
  hosts: dbserver
  become: true
  become_method: su

  tasks:

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: files/agrosmart.zip
      dest: /home/webuser